### ISSUE TITLE
Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default

### ISSUE THREAD

**Issue by denisshetkin** [nunit/docs#220] opened 2017-07-06 09:08 UTC
Hi. 
I downloaded latest version (3.7.1), and trying to build it in visual studio.
But catching these error msg:
"Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default"
for any project.

Can you help me please, how to solve this problem, because changing <LangVersion> tag in csproj file does not fix it :(

To tell the truth i need to build it for 4.6.1 framework, because you didn't build nUnit for 4.6.1, and i need to do it by myself.

**Comment by immeraufdemhund** [comment] 2017-07-06 12:48
At work I use NUnit for my projects and my projects are 4.5.2, 4.6.1, and 4.6.2. Are you adding NUnit through NuGet, if you are it should work just fine.

**Comment by jnm2** [comment] 2017-07-08 14:21
> "Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default"

You can't build unless you have either VS2015 or VS2017.

> To tell the truth i need to build it for 4.6.1 framework, because you didn't build nUnit for 4.6.1, and i need to do it by myself.

@immeraufdemhund is right. There is no need for anyone to build for .NET Framework 4.6.1 because we already distribute a build for .NET Framework 4.5 and you can always reference a library that targets a lower version of the .NET Framework.

**Comment by jnm2** [comment] 2017-07-08 14:22
Whether via NuGet, or even directly.

**Comment by jnm2** [comment] 2017-07-08 14:23
(Side: if we wanted to support super old versions of csc.exe, we'd have to make all our `<LangVersion>` tags conditional.)

**Comment by jnm2** [comment] 2017-07-15 23:13
@denisshetkin Does that answer your question? Do you need to see a sample project which targets .NET Framework 4.6.1 and references the distributed NUnit Framework?

**Comment by jimmy9988** [comment] 2017-10-13 18:16
I can build it with latest visual studio 2017, but get the same error messages when I try to build it using the build script.
```
Microsoft (R) Build Engine version 4.7.2046.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

CSC : error CS1617: Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default [C:\Users\enhsu\git\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
```

Some how the build script references the old version msbuild and gets the wrong .net framework.

**Comment by immeraufdemhund** [comment] 2017-10-13 19:36
most build scripts i've worked with need the correct msbuild to use. There are many ways to achieve this but it depends on your system

**Comment by mikkelbu** [comment] 2017-10-15 06:25
Hi @jimmy9988 can you provide how you invoked the build-script and the full log from the build-script. I think this is a Cake problem, but it would be great to get it solved.

**Comment by jimmy9988** [comment] 2017-10-16 01:56
The error happens when calling Cake DotNetBuild to build all projects.
I think 4.0 is the newest msbuild it can find in my environment when I ran it. I guess it gets it from registry at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\`.
However, I believe to support C#6, you at least need msbuild > 14.0.
One solution for people want to build it might be installing [msbuild 14.0](https://www.microsoft.com/en-us/download/details.aspx?id=48159), but you'll still get other errors when building NetStandard13 and NetStandard16.

I can finally have everything built after I install the [Build Tools for Visual Studio 2017](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15), which contains msbuild 15.

So to build NUnit, you can either:
1. Use visual studio 2017 to build this.
2. Install Build Tools for Visual Studio 2017 and run build.cmd.

I'm not familiar with NUnit, and not sure how to better address this. However, to people who try to build NUnit with the build script it will be really difficult to get the cause of error `"Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default"`

FYI, here is the full log I got:
```
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Compiling build script...

----------------------------------------
Setup
----------------------------------------
Executing custom setup action...
Building Release version 3.9.0 of NUnit.
Checking if .NET Core SDK is installed
1.0.0-preview2-003121

========================================
InitializeBuild
========================================
Executing task: InitializeBuild
Restoring NuGet package src/NUnitFramework/framework/packages.config
All packages listed in packages.config are already installed.
Restoring NuGet package src/NUnitFramework/nunitlite/packages.config
All packages listed in packages.config are already installed.
Restoring NuGet package src/NUnitFramework/nunitlite.tests/packages.config
All packages listed in packages.config are already installed.
Restoring NuGet package src/NUnitFramework/testdata/packages.config
All packages listed in packages.config are already installed.
Restoring NuGet package src/NUnitFramework/tests/packages.config
All packages listed in packages.config are already installed.
Restoring .NET Core packages
log  : Restoring packages for D:\nunit\src\NUnitFramework\framework\nunit.framework-4.5.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\framework\nunit.framework-netstandard16.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-2.0.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\framework\nunit.framework-3.5.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\framework\nunit.framework-4.0.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\framework\nunit.framework-netstandard13.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\framework\nunit.framework-2.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\framework\nunit.framework-4.0.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\framework\nunit.framework-4.5.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-2.0.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\framework\nunit.framework-2.0.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\framework\nunit.framework-3.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\framework\nunit.framework-4.0.project.json
log  : Restore completed in 83ms.
log  : D:\nunit\src\NUnitFramework\framework\nunit.framework-2.0.project.json
log  : Restore completed in 83ms.
log  : D:\nunit\src\NUnitFramework\framework\nunit.framework-4.5.project.json
log  : Restore completed in 84ms.
log  : D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-2.0.project.json
log  : Restore completed in 83ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-3.5.project.json...
log  : D:\nunit\src\NUnitFramework\framework\nunit.framework-3.5.project.json
log  : Restore completed in 85ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-4.5.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-4.5.project.lock.json
log  : Restoring packages for D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-netstandard16.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite\nunitlite-2.0.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-netstandard13.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-3.5.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite\nunitlite-2.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-4.5.project.json
log  : Restore completed in 22ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite\nunitlite-3.5.project.json...
log  : D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-3.5.project.json
log  : Restore completed in 38ms.
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite\nunitlite-3.5.project.lock.json
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite\nunitlite-4.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite\nunitlite-4.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite\nunitlite-2.0.project.json
log  : Restore completed in 26ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite\nunitlite-4.5.project.json...
log  : D:\nunit\src\NUnitFramework\nunitlite\nunitlite-4.0.project.json
log  : Restore completed in 2ms.
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite\nunitlite-4.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite\nunitlite-3.5.project.json
log  : Restore completed in 13ms.
log  : D:\nunit\src\NUnitFramework\nunitlite\nunitlite-4.5.project.json
log  : Restore completed in 8ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite\nunitlite-netstandard13.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite\nunitlite-netstandard16.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-2.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-2.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-2.0.project.json
log  : Restore completed in 28ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-3.5.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-3.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-3.5.project.json
log  : Restore completed in 1ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-4.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-4.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-4.0.project.json
log  : Restore completed in 10ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-4.5.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-4.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-4.5.project.json
log  : Restore completed in 22ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-netstandard13.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite\nunitlite-netstandard13.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-netstandard13.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\framework\nunit.framework-netstandard13.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\framework\nunit.framework-netstandard16.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite\nunitlite-netstandard13.project.json
log  : Restore completed in 406ms.
log  : D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-netstandard13.project.json
log  : Restore completed in 468ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-2.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-2.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-2.0.project.json
log  : Restore completed in 3ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-3.5.project.json...
log  : D:\nunit\src\NUnitFramework\framework\nunit.framework-netstandard16.project.json
log  : Restore completed in 558ms.
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-3.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\framework\nunit.framework-netstandard13.project.json
log  : Restore completed in 573ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-4.5.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-4.0.project.json...
log  : D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-3.5.project.json
log  : Restore completed in 21ms.
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-4.5.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-4.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-4.5.project.json
log  : Restore completed in 8ms.
log  : D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-4.0.project.json
log  : Restore completed in 30ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-2.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-2.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-2.0.project.json
log  : Restore completed in 23ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-3.5.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-3.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-3.5.project.json
log  : Restore completed in 22ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-4.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-4.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-4.0.project.json
log  : Restore completed in 10ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-4.5.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-4.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-4.5.project.json
log  : Restore completed in 18ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-netstandard16.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-netstandard13.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-netstandard16.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-netstandard13.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-netstandard16.project.lock.json
log  : D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-netstandard16.project.json
log  : Restore completed in 681ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-netstandard16.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite\nunitlite-netstandard16.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite\nunitlite-netstandard16.project.json
log  : Restore completed in 688ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\testdata\nunit.testdata-2.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\testdata\nunit.testdata-2.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\testdata\nunit.testdata-2.0.project.json
log  : Restore completed in 6ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\testdata\nunit.testdata-3.5.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\testdata\nunit.testdata-3.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\testdata\nunit.testdata-3.5.project.json
log  : Restore completed in 25ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\testdata\nunit.testdata-4.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\testdata\nunit.testdata-4.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\testdata\nunit.testdata-4.0.project.json
log  : Restore completed in 12ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\testdata\nunit.testdata-4.5.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\testdata\nunit.testdata-4.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\testdata\nunit.testdata-4.5.project.json
log  : Restore completed in 17ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\testdata\nunit.testdata-netstandard13.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-netstandard13.project.lock.json
log  : D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-netstandard13.project.json
log  : Restore completed in 386ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\testdata\nunit.testdata-netstandard16.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\testdata\nunit.testdata-netstandard13.project.lock.json
log  : D:\nunit\src\NUnitFramework\testdata\nunit.testdata-netstandard13.project.json
log  : Restore completed in 289ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-2.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-2.0.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-netstandard16.project.lock.json
log  : D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-2.0.project.json
log  : Restore completed in 30ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-3.5.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-3.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-3.5.project.json
log  : Restore completed in 3ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-4.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-4.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-4.0.project.json
log  : Restore completed in 2ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-4.5.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-4.5.project.lock.json
log  : D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-4.5.project.json
log  : Restore completed in 13ms.
log  : D:\nunit\src\NUnitFramework\slow-tests\slow-nunit-tests-netstandard16.project.json
log  : Restore completed in 518ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-netstandard13.project.json...
log  : Restoring packages for D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-netstandard16.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\testdata\nunit.testdata-netstandard16.project.lock.json
log  : D:\nunit\src\NUnitFramework\testdata\nunit.testdata-netstandard16.project.json
log  : Restore completed in 415ms.
log  : Restoring packages for D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-4.0.project.json...
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-4.0.project.lock.json
log  : D:\nunit\src\NUnitFramework\mock-assembly\mock-assembly-4.0.project.json
log  : Restore completed in 11ms.
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-netstandard13.project.lock.json
log  : D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-netstandard13.project.json
log  : Restore completed in 320ms.
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-netstandard16.project.lock.json
log  : D:\nunit\src\NUnitFramework\tests\nunit.framework.tests-netstandard16.project.json
log  : Restore completed in 382ms.
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-netstandard13.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-netstandard13.project.json
log  : Restore completed in 2270ms.
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-netstandard13.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-netstandard13.project.json
log  : Restore completed in 2035ms.
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-netstandard16.project.lock.json
log  : Writing lock file to disk. Path: D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-netstandard16.project.lock.json
log  : D:\nunit\src\NUnitFramework\nunitlite-runner\nunitlite-runner-netstandard16.project.json
log  : Restore completed in 2198ms.
log  : D:\nunit\src\NUnitFramework\nunitlite.tests\nunitlite.tests-netstandard16.project.json
log  : Restore completed in 2149ms.
Finished executing task: InitializeBuild

========================================
Build45
========================================
Executing task: Build45
Microsoft (R) Build Engine version 4.7.2046.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

CSC : error CS1617: Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default [D:\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
An error occurred when executing task 'Build45'.

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Error: MSBuild: Process returned an error (exit code 1).
```

**Comment by jnm2** [comment] 2017-10-16 12:57
> I can finally have everything built after I install the Build Tools for Visual Studio 2017, which contains msbuild 15.

@rprouse, since we have a dependency on this anyway, maybe we should just make it explicit by moving forward with https://github.com/nunit/nunit/pull/2380 and the modern SDK .csproj since this is the state of reality right now anyway?

**Comment by rprouse** [comment] 2017-10-25 02:06
@jnm2 I think I agree. A hard dependency seems to have crept in on 2017 despite my jumping through hoops to maintain backwards compatibility by compiling the .NET Standard projects as PCL. The new SDK projects are so much cleaner and nicer to work with. It would also allow us to stop pinning the .NET Core version in `global.json` to the older version and use the version that gets installed with Visual Studio.

I am going to dust off that PR and check the current state of it on various platforms. I will report back there.

**Comment by jadarnel27** [comment] 2018-02-21 15:01
Since nunit/nunit#2380 has been merged, is this issue solved?

**Comment by rprouse** [comment] 2018-02-21 15:27
@jadarnel27 are you trying to build the NUnit framework from our GitHub repository, or are you running into this error building your test projects using the NUnit NuGet packages?

This is fixed for building the NUnit Framework itself. If you are having problems building NUnit, do you have Visual Studio 2017 installed? Are you using the Visual Studio 2017 command prompt for command line builds to setup your environment variables and paths correctly?

If you are having problems building your own projects, then we will need more information from you. What framework are you targeting, what version of Visual Studio, how are you including NUnit, etc.

**Comment by rprouse** [comment] 2018-02-21 15:28
I am closing this issue as it has been resolved. @jadarnel27 feel free to comment if you are having issues, we will see it.

**Closed by rprouse** 2018-02-21 15:28 UTC

**Comment by jadarnel27** [comment] 2018-02-21 15:47
@rprouse Sorry for my vague comment 😄  I am not having any problems, I was just reviewing the issues in the docs repo to see if there were any that could easily be resolved / closed.
