### ISSUE TITLE
Support Multiple asserts

### ISSUE THREAD

**Issue by RalfKoban** [nunit/docs#18] opened 2016-03-10 09:30 UTC
Hi,

it would be nice to have multiple asserts support, as described here:
https://github.com/nunit/dev/wiki/Multiple-Asserts

Background:
Having that supported, it would be much easier to convert existing NUnit 2.6 tests using [TestCaseSource] (that rely on the fact that the source does not need to be static) into NUnit 3 tests (where the source must be static) with getting almost similar behavior.

BR,
Ralf

**Comment by rprouse** [comment] 2016-03-10 14:54
Closing as a duplicate of nunit/nunit#391, feel free to comment on that issue.

**Closed by rprouse** 2016-03-10 14:54 UTC
