### ISSUE TITLE
Add documentation on how to install extensions

### ISSUE THREAD

**Issue by DannyCork** [nunit/docs#137] opened 2016-11-04 10:12 UTC
Hi,
I'd like to run nunit 2.6.4 test using the nunit3 console. The docs state 

> If the NUnit V2 framework driver is installed, test assemblies may be run based on any version of the NUnit framework beginning with 2.0. Without the V2 driver, only version 3.0 and higher tests may be run.

Where do I find the V2 driver?

Thanks.

**Comment by rprouse** [comment] 2016-11-04 11:42
How are you installing the console? MSI or NuGet.

**Comment by DannyCork** [comment] 2016-11-04 12:02
downloaded the NUnit.3.5.0.zip zip from https://github.com/nunit/nunit-console/releases/tag/3.5

![zip](https://cloud.githubusercontent.com/assets/3512672/20004837/6b950c46-a286-11e6-9a9b-3b76ba8b5fb2.png)

**Comment by ChrisMaddock** [comment] 2016-11-04 12:09
In that case, the v2 driver should be in the `addins` directory, and already loaded. Use the `--list-extensions` flag in nunit3-console to check what's available.

This probably highlights a gap in our docs, we should maybe have a page on how to install/use extensions, given that differs between msi/zip/nuget. I'll re-title this issue to represent that.

**Comment by ChrisMaddock** [comment] 2017-05-30 11:59
This is a duplicate of https://github.com/nunit/docs/issues/11

**Closed by ChrisMaddock** 2017-05-30 11:59 UTC
Labels: is:newpage, pri:high
