### ISSUE TITLE
Explicit tests are run when excluding more than one category

### ISSUE THREAD

**Issue by starteleport** [nunit/docs#48] opened 2016-04-14 11:05 UTC
Hello! I've got a test fixture like this
```
    [TestFixture]
    public class TestClass
    {
        [Test]
        [Explicit]
        public void Explicit_Should_NeverRun() => Assert.Fail();

        [Test]
        [Category1]
        public void Category1() => Assert.Pass();

        [Test]
        [Category2]
        public void Category2() => Assert.Pass();

        [Test]
        public void BasicTest() => Assert.Pass();
    }

    public class Category1Attribute : CategoryAttribute
    {
    }

    public class Category2Attribute : CategoryAttribute
    {
    }
```

The problem is that, when I run `.\nunit3-console.exe .\NUnitAttributeTests.dll --where="cat != Category1 && cat != Category2"`, it executes explicit test, too ([this page](https://github.com/nunit/docs/wiki/Explicit-Attribute) states that it shouldn't). 

Is there a way to exclude explicit tests explicitly :smiley: in such a situation?

**Comment by CharliePoole** [comment] 2016-04-14 11:45
Duplicate of nunit/nunit#1141. For nunit issues please use the nunit repo and check to see if the problem is already reported.

As a temporary workaround this might work:
!(cat == Category1 || cat == Category2)

**Closed** 2016-04-14 11:46 UTC

**Comment by starteleport** [comment] 2016-04-14 12:47
Thank you. Didn't notice I was searching and posting the issue to docs repository.
