### ISSUE TITLE
NUnit Test error : An exception occurred in the driver while loading tests

### ISSUE THREAD

**Issue by manojmsrit** [nunit/docs#312] opened 2019-05-22 18:26 UTC
Time Elapsed 00:00:01.58
+ mono /Users/manojdeshpande/Downloads/NUnit.Console-3.10.0/bin/net20/nunit3-console.exe Test.kommmit.Offers/Test.kommmit.Offers.csproj --result=nunit-result1.xml -config=Debug
NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
Wednesday, May 22, 2019 8:23:58 PM

Runtime Environment
   OS Version: MacOSX 17.7.0.0 
  CLR Version: 4.0.30319.42000

Test Files
    Test.kommmit.Offers/Test.kommmit.Offers.csproj

Errors, Failures and Warnings

1) Error : /Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/Test.kommmit.Offers/Test.kommmit.Offers.csproj
NUnit.Engine.NUnitEngineException : An exception occurred in the driver while loading tests.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'nunit.framework, Version=3.11.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies
--NUnitEngineException
An exception occurred in the driver while loading tests.

Server stack trace: 
  at NUnit.Engine.Runners.DirectTestRunner.LoadDriver (NUnit.Engine.Extensibility.IFrameworkDriver driver, System.String testFile, NUnit.Engine.TestPackage subPackage) [0x0003a] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.DirectTestRunner.LoadPackage () [0x000c8] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.TestDomainRunner.LoadPackage () [0x00017] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded () [0x00008] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.DirectTestRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.AbstractTestRunner.Run (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Agents.RemoteTestAgent.Run (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at (wrapper managed-to-native) System.Runtime.Remoting.RemotingServices.InternalExecute(System.Reflection.MethodBase,object,object[],object[]&)
  at System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (System.MarshalByRefObject target, System.Runtime.Remoting.Messaging.IMethodCallMessage reqMsg) [0x000b5] in <bb7b695b8c6246b3ac1646577aea7650>:0 

Exception rethrown at [0]: 
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_remoting_wrapper(intptr,intptr)
  at (wrapper remoting-invoke) NUnit.Engine.Agents.RemoteTestAgent.Run(NUnit.Engine.ITestEventListener,NUnit.Engine.TestFilter)
  at NUnit.Engine.Runners.ProcessRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00025] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
--
FileNotFoundException
Could not load file or assembly 'nunit.framework, Version=3.11.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies

Server stack trace: 
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity) [0x00076] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName,System.Security.Policy.Evidence)
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef) [0x00000] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName)
  at System.Reflection.Assembly.Load (System.Reflection.AssemblyName assemblyRef) [0x00005] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName (System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity, System.Reflection.RuntimeAssembly reqAssembly, System.Threading.StackCrawlMark& stackMark, System.Boolean throwOnFileNotFound, System.Boolean forIntrospection, System.Boolean suppressSecurityChecks) [0x0002e] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at System.Activator.CreateInstance (System.String assemblyString, System.String typeName, System.Boolean ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityInfo, System.Threading.StackCrawlMark& stackMark) [0x00049] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at System.Activator.CreateInstance (System.String assemblyName, System.String typeName, System.Boolean ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityInfo) [0x00016] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at System.AppDomain.CreateInstance (System.String assemblyName, System.String typeName, System.Boolean ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityAttributes) [0x0000e] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain.CreateInstance(string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[],System.Security.Policy.Evidence)
  at System.AppDomain.CreateInstanceAndUnwrap (System.String assemblyName, System.String typeName, System.Boolean ignoreCase, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityAttributes) [0x00000] in <bb7b695b8c6246b3ac1646577aea7650>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain.CreateInstanceAndUnwrap(string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[],System.Security.Policy.Evidence)
  at (wrapper xdomain-dispatch) System.AppDomain.CreateInstanceAndUnwrap(object,byte[]&,byte[]&,string,string,bool)

Exception rethrown at [0]: 
  at (wrapper xdomain-invoke) System.AppDomain.CreateInstanceAndUnwrap(string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[],System.Security.Policy.Evidence)
  at (wrapper remoting-invoke-with-check) System.AppDomain.CreateInstanceAndUnwrap(string,string,bool,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo,object[],System.Security.Policy.Evidence)
  at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject (System.String typeName, System.Object[] args) [0x00011] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load (System.String testAssemblyPath, System.Collections.Generic.IDictionary`2[TKey,TValue] settings) [0x00041] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.DirectTestRunner.LoadDriver (NUnit.Engine.Extensibility.IFrameworkDriver driver, System.String testFile, NUnit.Engine.TestPackage subPackage) [0x00008] in <d5dabe0b10664f5d8da90fb102a841f8>:0 

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-05-22 18:23:58Z
    End time: 2019-05-22 18:23:59Z
    Duration: 0.828 seconds

Results (nunit3) saved as nunit-result1.xml
Build step 'Execute shell' marked build as failure
Recording NUnit tests results
ERROR: Step ‘Publish NUnit test result report’ failed: No test report files were found or the NUnit input XML file contained no tests.
Finished: FAILURE

**Comment by ChrisMaddock** [comment] 2019-05-26 10:53
Duplicate of https://github.com/nunit/docs/issues/312

**Closed by ChrisMaddock** 2019-05-26 10:53 UTC

**Comment by mikkelbu** [comment] 2019-05-26 10:59
@ChrisMaddock Don't you mean #311?

**Comment by ChrisMaddock** [comment] 2019-05-26 11:05
I do - thanks!

**Comment by manojmsrit** [comment] 2019-05-26 11:53
Hello, sorry again. I came up with new error, I am getting below error when i try to use "dotnet test", can you please suggest me regarding this

+ dotnet test Test.kommmit.Offers/Test.kommmit.Offers.csproj
Build started, please wait...
/usr/local/share/dotnet/sdk/2.2.107/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETPortable,Version=v4.5,Profile=Profile259" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/kommmit.Offers/kommmit.Offers/kommmit.Offers.csproj]
/usr/local/share/dotnet/sdk/2.2.107/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETPortable,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. 


Before this error i got one more error shown as below which i resolved by updating path of "Microsoft.Portable.CSharp.targets" manually.

+ dotnet test Test.kommmit.Offers/Test.kommmit.Offers.csproj
Build started, please wait...
/Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/kommmit.Offers/kommmit.Offers/kommmit.Offers.csproj(220,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/2.2.107/Microsoft/Portable/v4.5/Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by mikkelbu** [comment] 2019-05-26 20:02
Looks like your installation of .NET core does not have the referenced variant installed ".NETPortable,Version=v4.5,Profile=Profile259", but this is more a dotnet problem than NUnit, as the code fails in the build step. Sorry that I cannot help you more, but my knowledge about dotnet core on Linux/macOS is very limited.

Ps. There is no need to write both in this issue and in #311 as most of us will get notifications for all messages, meaning that we will get the messages twice.
