### ISSUE TITLE
Missing links from Classic Assertions to Constraints

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#101] opened 2016-08-12 12:40 UTC
Most of the classic assertion pages have "See also:" links to the related constraint, but most of these are dead links. We should fill them in at some point. :smile: 

Quite a few are looking for 'constraint category' pages (e.g. "See also: Collection Constraints") - they could probably just link to the relevant section of https://github.com/nunit/docs/wiki/Constraints

I'm referring to the sub-pages of this page:
https://github.com/nunit/docs/wiki/Classic-Model

**Comment by CharliePoole** [comment] 2016-08-12 12:48
I see what you mean. Good to document this so somebody may eventually make a concerted effort to fix them all. FYI I generally just fix single errors when I browse the page and see them - but this isn't an area I would normally browse.

I left the "bug" label here for errors such as we occasionally get that go beyond creating or updating pages and relate to the wiki as a whole. They can't be resolved by editing in the wiki. An example would be an NUnit page that shows up with the top-level menu rather than the NUnit menu.

**Comment by ChrisMaddock** [comment] 2016-08-12 12:58
Sure. :+1: I'll probably go through on the plane at some point, sounds suitably mindless!

Related question: was it a deliberate decision to not have the classic-model page on the main menu, to discourage use, or just a side effect? Should we have two submenu items under 'Assertions'?

**Comment by CharliePoole** [comment] 2016-08-12 13:08
Neither the classic model page nor the constraint-model page are on the main menu. They don't cover things that users are generally looking for and are more like background explaining the difference. They are both linked from the Assertions page.

**Comment by ChrisMaddock** [comment] 2016-08-12 13:23
Sorry, I don't think I was clear. I was thinking that:

https://github.com/nunit/docs/wiki/Classic-Model (not in sidebar)

is somewhat equivalent to:

https://github.com/nunit/docs/wiki/Constraints (is in sidebar)

Agreed that `/wiki/Constraint-Model` is in the right place. But I wondered if these two 'menu' pages for the two different assertion models should be equally accessible - unless we're trying to promote the constraint way of writing tests.

**Comment by CharliePoole** [comment] 2016-08-12 13:57
Hmmm... I agree that the two (Classic-Model and Constraints) are _somewhat_ equivalent. :-)

Constraints has a list of constraints.
Classic-model has a list of asserts.

The classic model is antiquated and we are not merely promoting the constraint model - rather it has been our standard way to write assertions for four or five years. The classic model remains for support of people who never made the transition. In the past, I've advocated making it much less visible than it now is (separate namespace, assembly even) but too many people still like it. :-)

On a related matter, we don't normally add any new features in the classic model. By design, the features of the constraint model are a true superset of those in the classic model. That is, there should be nothing that you can do in the classic model that can't be done in the constraint model.

**Closed** 2016-09-05 16:23 UTC
Labels: for:framework, is:update, pri:normal
