### ISSUE TITLE
Additional information required regarding name formatting, string argument truncation

### ISSUE THREAD

**Issue by tonyhallett** [nunit/docs#300] opened 2019-02-27 13:39 UTC
The default behaviour of {a} is not to truncate ( although this is the behaviour defined in Generation of Test Names Spec ) whereas for specific arguments e.g {0} truncates to 40.  The [Wiki](https://github.com/nunit/docs/wiki/Template-Based-Test-Naming) does not mention this behaviour 'String arguments may be truncated to a maximum length. Either the {a} specifier or any of the individual argument specifiers may be followed by a colon and a length:'.  This suggests, to me, that there should be no truncation unless explicitly specified.

Additionally, shouldn't the behaviour be the same ?

Please remove Generation of Test Names Spec from specifications now it has been implemented and the Wiki page present.

**Comment by CharliePoole** [comment] 2019-02-27 15:57
The specifications are not there for user info. They were orginally in a separate wiki, which we haven't had for years and were transferred to the documentation wiki with the intent of phasing them out. This was a project of mine a few years back and I removed a great many specs (much more than what remains) and categorized others as implemented, partial, etc.

This particular spec is the only one I marked as implemented without removing it. That's because it needs to be reviewed by other team members to ensure there is nothing else that is planned for implementation at this point. From my side, I agree with @tonyhallett that it should be removed.

It also seems to me that if these specs are not going to be cleaned up and retired soon, they should probably be somewhere else where they won't confuse users.

I believe the actual documentation page describes current behavior correctly, as it should do.

**Comment by tonyhallett** [comment] 2019-03-02 13:57
I think the current documentation does not fully describe behaviour. It specifies that string arguments may be truncated but fails to mention individual arguments will be truncated unless followed by :0. I also think it is a fair assumption that default behaviour would be the same given that the truncation length in {a} is for the truncation of individual parameters.

**Comment by CharliePoole** [comment] 2019-03-02 16:46
If individual arguments specified as `{o}` are being truncated, I would say that's a code bug not a documentation bug. Both `{a}` and `{o}` are supposed to display the entire value, not truncate.

If this is a bug, the root cause is probably lack of tests.

**Comment by tonyhallett** [comment] 2019-03-02 19:30
Ok I will look at the existing tests. Thanks

**Comment by ChrisMaddock** [comment] 2019-05-26 11:08
This was a bug which has now been fixed, thanks @tonyhallett!

**Closed by ChrisMaddock** 2019-05-26 11:08 UTC
