### ISSUE TITLE
Question: SetUpFixture Behavior with Nested Namespaces

### ISSUE THREAD

**Issue by Gwindalmir** [nunit/docs#327] opened 2019-12-05 21:37 UTC
I have tests that use SetUpFixture to execute code before the start of every fixture.
But I noticed something, and the documentation wasn't clear on the expected behavior.

For example, say I have a class like this:
```
namespace NUnitTests
{
    [SetUpFixture]
    public class TestSetupAndTeardown
    {
          [OneTimeSetUp]
          public void OneTimeSetUp()
          {
              // blah
          }
    }
}

```
And my test class:
```
namespace NUnitTests.Internals
{
    public class SomeTests
    {
        [Test]
        public void TestSomething()
        {
            // Blah
        }
    }
}
```

The fixture setup will still run when starting up the SomeTests class, even though the namespace is technically different.
The documentation at https://github.com/nunit/docs/wiki/SetUpFixture-Attribute states:

> This is the attribute that marks a class that contains the one-time setup or teardown methods for all the test fixtures under a given namespace.

My question: is it intended that nested namespaces are also included in that? In other words, do nested namespaces count as being "under" the according namespace?

Additionally:

> Multiple SetUpFixtures may be created in a given namespace. The order of execution of such fixtures is indeterminate.

Assuming the previous behavior is intentional, is this also true for nested namespaces?
For classes in the same exact namespace, I'd expect an unknown execution order, but for nested namespaces, I could see a fairly defined behavior (either sub-namespaces first, then parent; or parent namespace first, then children, siblings again in undefined order).

Either way, I'm not trying to report a bug against NUnit for the behavior, I just want some clarification in the documentation.

**Comment by mikkelbu** [comment] 2019-12-06 20:20
> My question: is it intended that nested namespaces are also included in that? In other words, do nested namespaces count as being "under" the according namespace?

Yes. I've not written this text, but I think it is quite common to use "under" to mean the same namespace or nested namespaces. If it should only be in the same namespace, then I think the text should have been `"all the test fixtures in a given namespace."` or `"all the test fixtures in the same namespace."`, and not `"all the test fixtures under a given namespace."`.

> Assuming the previous behavior is intentional, is this also true for nested namespaces?

Yes. Generally, we don't assume any ordering as this would make it more difficult to change the implementation later on.

Ps. I just took a look at the code and it seems that the classes are examined in the order returned from `Assembly.GetTypes()` and that order is not specified.

**Comment by CharliePoole** [comment] 2019-12-06 21:00
Yes... we use the word "under" that way in lots of places in the docs wrt namespaces. I'm the culprit here. I was trained early in my work career to systematically use the same word for a particular meaning, but in this case I guess "under" doesn't always seem as clear to other folks as it did to me at the time.We should change this as we find it it the docs.

WRT the order of execution of setup (also one-time setup) it's deterministic between namespaces (including nested namespaces) but non-deterministic if you have two setups at the same level, e.g. two methods in the same class marked [SetUp]. That's, however, a usage that should only come up in limited situations and is easy to avoid.

The defined order is as follows...

1. Setup starts at the assembly level `SetUpFixture`, outside of any namespace.

2. It continues with the top level of any `SetUpFixtures` in a namespace namespaces, proceeds downward into any nested namespaces.

3. Setup code in a `TestFixture` comes after any `SetUpFixture`s that control the namespace of the fixture.

4. At each of the above levels, inheritance may also come into play. Base class setups are run before those of the derived class.

5. Ordering of `TestFixtures` or `SetUpFixtures` within the same namespace is indeterminate.

6. Ordering of multiple setup methods within the same class is indeterminate.

[Items 5 and 6 rarely come into play but the features are available for situations like code generation, where it may be more convenient to have multiple setup fixtures and/or methods.]

I'll take a look at the doc to see what changes seem needed.

**Comment by Gwindalmir** [comment] 2019-12-07 04:13
@CharliePoole thanks for that information!

**Comment by ChrisMaddock** [comment] 2020-06-13 17:58
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂

**Closed by ChrisMaddock** 2020-06-13 17:58 UTC
Labels: is:question

**Comment by danielschilling-ml** [comment] 2023-04-12 18:29
The [documentation](https://docs.nunit.org/articles/nunit/writing-tests/attributes/setupfixture.html) is even more confusing on this point now. Now it seems to actively contradict the actual behavior:

> A SetUpFixture in a namespace will apply tests to that exact namespace only, and not to any namespaces below it.

**Comment by CharliePoole** [comment] 2023-04-12 18:41
@danielschilling-ml I think I may have written that text.

NUnit understands all test fixtures and tests in a namespace _or a contained namespace_ to be "in" that enclosing namespace. It will run the one time setup, then all the tests in the namespace _or in contained namespaces_ and finally the one time teardown.

If that's not happening, you may have found an NUnit framework bug. However, if you are somehow the one time setup to run once per contained namespace rather than just one time, you have misunderstood the docs.

Looked at in another way... namespaces may be considered either as separate entities with names like

```
A
A.B
A.B.X
A.B.Y
A.C
```

or as a hierarchy, with B "inside" A, etc...

```
A
  B
    X
    Y
  C
```

NUnit treats them in the latter way. In fact, each namespace is considered as a "Test" internally.

**Comment by danielschilling-ml** [comment] 2023-04-12 19:25
@CharliePoole  Yes, it is behaving the way you describe, hierarchically, so this is not a bug in the framework. A test fixture named `MyProject.Tests.Services.WidgetTests` would run both of these setup fixtures...

* `MyProject.Tests.ProjectSetup`
* `MyProject.Tests.Services.ServicesSetup`

The documentation however says they apply "*to that exact namespace only, and not to any namespaces below it*" - which sounds non-hierarchical, i.e. `testType.Namespace == setupFixtureType.Namespace` - an exact string comparison, meaning it would only execute `MyProject.Tests.Services.ServicesSetup`, and not `MyProject.Tests.ProjectSetup`.

Maybe it's a matter of interpretation. To me, the current documentation sounds like it is explicitly stating that this particular feature does *not* treat namespaces hierarchically, while in fact it does, and I am glad it does! I've benefited from this functionality for years. I was trying to help a colleague understand how to use it, and pointed him to the docs, where we encountered the confusing line of text.  I understand the term "under" like it's described in the earlier comments on this issue (i.e. in this or any nested namespaces), and also understand "below" to mean the same thing as "under".

**Comment by CharliePoole** [comment] 2023-04-12 20:24
I see. Weird!

@OsirisTerje I see you added that line to the page about six months ago. Perhaps you could take another look?

Alternatively, @danielschilling-ml, you can edit the page and ask for it to be reviewed. :-)

**Comment by benjaminsampica** [comment] 2023-09-22 00:46
I know this is closed, but this also confused me as well and I ended up here from that confusion. :)

**Comment by mikkelbu** [comment] 2023-10-22 12:31
I think the update in https://github.com/nunit/docs/pull/673/files was wrong. I'll create a new issue for this - #819

**Comment by OsirisTerje** [comment] 2023-10-22 17:35
1. We should then add into the docs the explantion that @CharliePoole gave https://github.com/nunit/docs/issues/327#issuecomment-1505755777
2. A code example, added to the snippets, demonstrating the behaviour would be nice.  It could also serve as the exploration for #819
